version: '3.0'

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./docker/nginx/conf.d/default.site:/etc/nginx/conf.d/default.site.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/var/www/html/

  php:
    restart: always
    build:
      context: ./docker/php
    links:
      - rabbit
    depends_on:
      - rabbit
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./html/:/var/www/html/

  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./docker/rabbit/data:/bitnami
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password